twig:
    default_path: '%kernel.project_dir%/templates'
    globals:
        menuService: "@app.menuService"

    paths:
        '%kernel.project_dir%/vendor/sbyaute/star-rating-bundle/Resources/views': SbyauteStarRatingBundle

when@test:
    twig:
        strict_variables: true
