twig:
    default_path: '%kernel.project_dir%/templates'
    globals:
        menuService: "@app.menuService"
        contactService: "@app.contactService"
        seoService: "@app.seoService"
        truncateHtmlService: "@app.truncateHtmlService"
        baseUrl: '%env(BASE_URL)%'

    paths:
        '%kernel.project_dir%/vendor/sbyaute/star-rating-bundle/Resources/views': SbyauteStarRatingBundle
        '%kernel.project_dir%/assets/': assets


when@test:
    twig:
        strict_variables: true
