twig:
    default_path: '%kernel.project_dir%/templates'
    globals:
        menuService: "@app.menuService"
        contactService: "@app.contactService"
        seoService: "@app.seoService"
        truncateHtmlService: "@app.truncateHtmlService"

    paths:
        '%kernel.project_dir%/vendor/sbyaute/star-rating-bundle/Resources/views': SbyauteStarRatingBundle

when@test:
    twig:
        strict_variables: true
